---
name: cmpsc-100-scholarly-template
break: true
indent: 4
---
# --> check the source code for various characteristics
# note that without an "--exact" the check is an "at least"
src:
    blank.py:
        ConfirmFileExists

worksheets:
    worksheet.py:
        ConfirmFileExists

# --> check the number of commits beyond a threshold
CountCommits --count 1
# --> check that the program executes and produces 1 lines of output
ExecuteCommand --command "pipenv run python3 src/blank.py"
ExecuteCommand --command "pipenv run python3 worksheets/worksheet.py"
CountCommandOutput --command "pipenv run python3 src/blank.py" --count 0
CountCommandOutput --command "pipenv run python3 worksheets/worksheet.py" --count 0
